# Generated by Django 5.1.1 on 2025-08-11 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='our_partner_and_location',
            name='Carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carrier'),
        ),
    ]
