# Generated by Django 5.1.1 on 2025-08-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_secondaryoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondaryoffer',
            old_name='Income',
            new_name='IncomeFrom',
        ),
        migrations.AddField(
            model_name='secondaryoffer',
            name='IncomeTO',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
