# Generated by Django 5.1.1 on 2025-08-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_income_secondaryoffer_incomefrom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondaryoffer',
            old_name='Agecover',
            new_name='AgeFrom',
        ),
        migrations.AddField(
            model_name='secondaryoffer',
            name='AgeTo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
