# Generated by Django 5.1.1 on 2025-08-25 22:10

import datetime
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_secondaryoffer_agefrom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=350)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CareersCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CareersDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CareersJobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CareersLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Frequently_Asked_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=300)),
                ('Answer', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='secondaryoffer',
            name='AgeFrom',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='secondaryoffer',
            name='AgeTo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='secondaryoffer',
            name='IncomeFrom',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='secondaryoffer',
            name='IncomeTO',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=100)),
                ('vacancy', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('SalaryRange', models.CharField(max_length=100)),
                ('PostDate', models.DateField(default=datetime.datetime(2025, 8, 26, 4, 10, 54, 11476))),
                ('short_description', models.TextField()),
                ('description', tinymce.models.HTMLField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.careersdepartment')),
                ('JobType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.careersjobtype')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.careerslocation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.careerscategory')),
            ],
        ),
    ]
