# Generated by Django 5.1.1 on 2025-08-26 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blog_careerscategory_careersdepartment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedCandidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=100)),
                ('Full_Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('CV', models.FileField(upload_to='Candidates_CV/')),
                ('Cover_Letter', models.TextField()),
                ('Application_Date', models.DateField(default=datetime.datetime(2025, 8, 26, 20, 2, 33, 106282))),
            ],
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 8, 26, 20, 2, 33, 106282)),
        ),
    ]
