# Generated by Django 5.1.1 on 2025-08-26 20:19

import datetime
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_appliedcandidates_alter_jobpost_postdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Description',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='Image',
            field=models.FileField(default='', upload_to='BlogImage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='readtime',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appliedcandidates',
            name='Application_Date',
            field=models.DateField(default=datetime.datetime(2025, 8, 27, 2, 18, 44, 385451)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 8, 27, 2, 18, 44, 383408)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 8, 27, 2, 18, 44, 385451)),
        ),
    ]
