# Generated by Django 5.1.1 on 2025-08-26 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_blog_description_blog_image_blog_readtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcandidates',
            name='Application_Date',
            field=models.DateField(default=datetime.datetime(2025, 8, 27, 2, 27, 44, 278476)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 8, 27, 2, 27, 44, 275473)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 8, 27, 2, 27, 44, 277504)),
        ),
    ]
