# Generated by Django 5.1.1 on 2025-08-26 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_appliedcandidates_application_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcandidates',
            name='Application_Date',
            field=models.DateField(default=datetime.datetime(2025, 8, 27, 2, 40, 35, 357238)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 8, 27, 2, 40, 35, 355195)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='readtime',
            field=models.CharField(default='5 min read', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 8, 27, 2, 40, 35, 357238)),
        ),
    ]
