# Generated by Django 5.2.5 on 2025-08-28 20:16

import datetime
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_appliedcandidates_application_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disclaimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disclaimer', tinymce.models.HTMLField()),
                ('Date', models.DateField(default=datetime.datetime(2025, 8, 29, 2, 16, 49, 11465))),
            ],
        ),
        migrations.CreateModel(
            name='Privacy_Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Privacy_Policy', tinymce.models.HTMLField()),
                ('Date', models.DateField(default=datetime.datetime(2025, 8, 29, 2, 16, 49, 10356))),
            ],
        ),
        migrations.CreateModel(
            name='Terms_of_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Terms_of_Service', tinymce.models.HTMLField()),
                ('Date', models.DateField(default=datetime.datetime(2025, 8, 29, 2, 16, 49, 10910))),
            ],
        ),
        migrations.AlterField(
            model_name='appliedcandidates',
            name='Application_Date',
            field=models.DateField(default=datetime.datetime(2025, 8, 29, 2, 16, 49, 13129)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 8, 29, 2, 16, 49, 9800)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 8, 29, 2, 16, 49, 12574)),
        ),
    ]
