# Generated by Django 3.2.25 on 2025-09-04 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_disclaimer_privacy_policy_terms_of_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcandidates',
            name='Application_Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 5, 1, 25, 47, 205337)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 5, 1, 25, 47, 202304)),
        ),
        migrations.AlterField(
            model_name='disclaimer',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 5, 1, 25, 47, 203340)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 9, 5, 1, 25, 47, 204334)),
        ),
        migrations.AlterField(
            model_name='privacy_policy',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 5, 1, 25, 47, 203340)),
        ),
        migrations.AlterField(
            model_name='terms_of_service',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 5, 1, 25, 47, 203340)),
        ),
    ]
