# Generated by Django 5.2.6 on 2025-09-22 18:03

import ckeditor_uploader.fields
import datetime
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20250905_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Canonical_Url',
            field=models.CharField(default='na', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='Meta_Description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='Meta_Titel',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='appliedcandidates',
            name='Application_Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 23, 0, 2, 59, 388968)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 23, 0, 2, 59, 385967)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[1920, 1080], upload_to='BlogImage/'),
        ),
        migrations.AlterField(
            model_name='disclaimer',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 23, 0, 2, 59, 386968)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 9, 23, 0, 2, 59, 388968)),
        ),
        migrations.AlterField(
            model_name='privacy_policy',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 23, 0, 2, 59, 386968)),
        ),
        migrations.AlterField(
            model_name='terms_of_service',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 23, 0, 2, 59, 386968)),
        ),
    ]
