# Generated by Django 5.2.6 on 2025-09-22 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_blog_canonical_url_blog_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcandidates',
            name='Application_Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 23, 0, 33, 42, 10542)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 23, 0, 33, 42, 10542)),
        ),
        migrations.AlterField(
            model_name='disclaimer',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 23, 0, 33, 42, 10542)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 9, 23, 0, 33, 42, 10542)),
        ),
        migrations.AlterField(
            model_name='privacy_policy',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 23, 0, 33, 42, 10542)),
        ),
        migrations.AlterField(
            model_name='terms_of_service',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 23, 0, 33, 42, 10542)),
        ),
    ]
