# Generated by Django 5.2.6 on 2025-09-24 17:50

import datetime
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_appliedcandidates_application_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accessibility', tinymce.models.HTMLField()),
                ('Date', models.DateField(default=datetime.datetime(2025, 9, 24, 23, 50, 11, 660379))),
            ],
        ),
        migrations.AlterField(
            model_name='appliedcandidates',
            name='Application_Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 24, 23, 50, 11, 662389)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 24, 23, 50, 11, 657834)),
        ),
        migrations.AlterField(
            model_name='disclaimer',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 24, 23, 50, 11, 660379)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 9, 24, 23, 50, 11, 661391)),
        ),
        migrations.AlterField(
            model_name='privacy_policy',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 24, 23, 50, 11, 659341)),
        ),
        migrations.AlterField(
            model_name='terms_of_service',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 24, 23, 50, 11, 659341)),
        ),
    ]
