# Generated by Django 5.2.6 on 2025-09-24 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_accessibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Prview',
            field=models.URLField(blank=True, default='https://policybear.com', help_text='Click To See Prview'),
        ),
        migrations.AlterField(
            model_name='accessibility',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 3, 38, 53, 29822)),
        ),
        migrations.AlterField(
            model_name='appliedcandidates',
            name='Application_Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 3, 38, 53, 32348)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 3, 38, 53, 28307)),
        ),
        migrations.AlterField(
            model_name='disclaimer',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 3, 38, 53, 29822)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 3, 38, 53, 30836)),
        ),
        migrations.AlterField(
            model_name='privacy_policy',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 3, 38, 53, 28307)),
        ),
        migrations.AlterField(
            model_name='terms_of_service',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 3, 38, 53, 29822)),
        ),
    ]
