# Generated by Django 5.2.6 on 2025-09-24 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_blog_prview_alter_accessibility_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Visibility',
            field=models.CharField(choices=[('Draft', 'Draft'), ('published', 'published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='accessibility',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 3, 58, 45, 161428)),
        ),
        migrations.AlterField(
            model_name='appliedcandidates',
            name='Application_Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 3, 58, 45, 163427)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 3, 58, 45, 159431)),
        ),
        migrations.AlterField(
            model_name='disclaimer',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 3, 58, 45, 161428)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 3, 58, 45, 163427)),
        ),
        migrations.AlterField(
            model_name='privacy_policy',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 3, 58, 45, 160426)),
        ),
        migrations.AlterField(
            model_name='terms_of_service',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 3, 58, 45, 161428)),
        ),
    ]
