# Generated by Django 5.1.1 on 2025-08-13 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carrier_alter_our_partner_and_location_carrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PolicyPlan', models.CharField(max_length=50)),
                ('Agecover', models.CharField(max_length=50)),
                ('Income', models.CharField(max_length=50)),
                ('Carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carrier')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
    ]
