# Generated by Django 5.1.1 on 2025-08-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_agecover_secondaryoffer_agefrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryoffer',
            name='AgeFrom',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='secondaryoffer',
            name='AgeTo',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='secondaryoffer',
            name='IncomeFrom',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='secondaryoffer',
            name='IncomeTO',
            field=models.IntegerField(max_length=50),
        ),
    ]
